name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact: windows

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v3
    - run: npm i --legacy-peer-deps
    - run: npm i --legacy-peer-deps
    - run: npm i luna-drag-selector --legacy-peer-deps
    - run: |
        npm run adb
        npm run server
        npm run scrcpy
        npm run build
        npm run pack
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          release/**/*.exe
          !release/**/win-unpacked/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/**/*.exe
        generate_release_notes: true
